//this is file for user's custom JS to be included into any HTML with rendered reportset data generated by izenda
if (typeof window.CustomScriptsAdded == 'undefined' || window.CustomScriptsAdded == null || !window.CustomScriptsAdded) {
  window.CustomScriptsAdded = true;
  window.CustomScriptsMessage = 'CustomScripts.js from Resources/FromDLL/Scripts included';
  //custom JS code should be placed after this comment

}